### ISSUE TITLE
Consider ordering results by spatial coverage

### ISSUE THREAD

**Issue by m-burgoyne** [opengeospatial/ogcapi-records#46] opened 2020-07-14 16:05 UTC
When a user searches a catalogue with a bounding box, records with global coverage will always be returned.  If the records in the response were ordered by the size of the spatial area that they represent, it would make it easier to identify information which was localised to the area that the user queried for.

**Comment by mhogeweg** [comment] 2020-07-14 16:59
that is true when you treat the bounding box coordinate as just number. we have implemented spatial ranking, based on both the area of the resource, the area of the search extent, and the area of overlap. The algorithm ranks those matching the search extent better higher than just something that has global coverage. This is combined with other search criteria.

**Comment by pvretano** [comment] 2020-08-24 14:26
24-AUG-2020: Spatial ranking makes sense; @tomkralidis in previous systems there was a flag to turn off results with global coverage; what about records without any spatial extent? 
Sorting is part of the core so a sortby clause could be used to direct the server about how to sort the result set by spatial extent.
If the request has a spatial predicate then records without extent should be ignored.

**Comment by ghobona** [comment] 2020-09-15 13:01
2020-09-15 OGC Member Meeting

This is a reasonable idea. However, we should not be restricted to only ordering by spatial extent. Michael Gordon.

There's a need to ensure that spatial sorting is well defined. Frederic Houbie.

In the previous meeting we agreed that we would not enforce this sorting/ordering capability. Angelos.

By writing a specification for spatial sorting, it would make it possible to predict the behaviour of the service. Frederic.

One would not expect an API to tell a developer how to sort the results. Michael Gordon.

If we cannot predict the behaviour then it should not be documented as a requirement. Frederic.

It should be at least optional. Jari.

**Comment by fhoubie** [comment] 2020-09-15 13:11
I agree API/interface is independent from the implementation, but even if it is optional, the expected behaviour shall be defined, otherwise, there is no need to specify it. When you specify the interface for a power plug, you still write on it the voltage, so the user knows what he can expect.

**Comment by mhogeweg** [comment] 2020-09-15 14:58
the API would tell the client what types of sorting are supported in the catalog. the standard does not need to prescribe one type of spatial sorting.  seems we're designing the entire implementation, not just the API.

**Comment by pvretano** [comment] 2020-09-21 14:20
12-SEP-2020: 
@JeffY we don't need to specify a default sort order in the core.
@cportele implementation are free to declare a default sort order in their OpenAPI document.
@cportele On the issue of **sortables**, might consider merging that somehow into the collection information to reduce the number of resources that a client has to hit in order to interact with the server.

**Comment by pvretano** [comment] 2020-11-02 15:35
2020-11-02: See https://github.com/opengeospatial/ogcapi-features/issues/424#issuecomment-720264251 which defines a schema that can be used for sortables as well.

**Comment by pvretano** [comment] 2020-11-30 15:22
2020-11-30: Don't want to define a default sort for queries and thus just leave it up to the server.  However, it might be a good idea to provide a mechanism to advertise or decalre the default sort.

**Comment by pvretano** [comment] 2021-05-03 14:26
05-MAY-2021: The default sort could be part of the OpenAPI definition or we could include a structure in the collection information like we do for CRS or other similar information.  We could have an array in the collection info and simply using the +/- syntax to declare the default sort.  With regard to "area", you would need a sortable named "area".  The fact that "area" may not actually be part of the underlying information model is not relevant, the server can derive that from the available information.
So what do we need in the specification?
(1) We need something in the collections information to allow the default sort orders to be declared.  An array of string where each string uses the +/- notation to indicate the default sort order that the corresponding sortable.
(2) We need to include some text concerning area.  If the server want to sort based on spatial coverage then it needs to declare an "area" sortable and then it can indicate the default sort order just like any other sortable in the collection information.  The use of "area" would be an example of how you can declare a virtual sortable.

**Comment by pvretano** [comment] 2022-10-05 02:08
See: https://github.com/opengeospatial/ogcapi-records/pull/185

**Comment by pvretano** [comment] 2023-04-21 15:14
21-APR-2023: Closing because the sorting capability in the API is moving to Features and Records will inherit the capability from there.  Also, #185 deals with the ability to declare the default sort order of any sortable including spatial sortables.  If further comments need to be added this should be done in Features.

**Closed by pvretano** 2023-04-21 15:14 UTC
